services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qcommerce_web_prod
    environment:
      - MIX_ENV=prod
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST:-qcommerce.localhost}
      - PORT=4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.qcommerce.rule=${HOSTS:-Host(`qcommerce.localhost`)}"
      - "traefik.http.services.qcommerce.loadbalancer.server.port=4000"
      - "traefik.http.routers.qcommerce.entrypoints=web,websecure"
      - "traefik.http.routers.qcommerce.tls=true"
      - "traefik.http.routers.qcommerce.tls.certresolver=myresolver"

networks:
  traefik-net:
    external: true
